import customtkinter as ctk
from inicio_sesion_registro import *
class registro:
    def __init__(self):
        self.ventana0=ctk.CTk()
        self.ventana0.geometry("800x600")
        self.labeluser=ctk.CTkLabel(self.ventana0,text="usuario: ")
        self.labeluser.pack(side="top")
        self.usuario=ctk.CTkEntry(self.ventana0)
        self.usuario.pack(side="top")
        self.labelpass=ctk.CTkLabel(self.ventana0,text="password: ")
        self.labelpass.pack(side="top")
        self.contraseña=ctk.CTkEntry(self.ventana0)
        self.contraseña.pack(side="top")
        self.boton_iniciar_sesion=ctk.CTkButton(self.ventana0,text="iniciar sesion",command=self.Back_iniciar_sesion)
        self.boton_iniciar_sesion.pack(side="top")
        self.boton_registrarse=ctk.CTkButton(self.ventana0,text="Registrarse",command=self.Front_registrarse)
        self.boton_registrarse.pack(side="top")
        self.boton_recuperar_contraseña=ctk.CTkButton(self.ventana0,text="recuperar contraseña",command=self.Front_olvido_contraseña)
        self.boton_recuperar_contraseña.pack(side="top")

        
        self.ventana0.mainloop()
    def Front_iniciar_sesion1(self):
        self.newlabeluser.forget()
        self.nuevo_usuario.forget()
        self.newlabelpass.forget()
        self.newlabelphone.forget()
        self.newlabelphone.forget()
        self.nuevo_celular.forget()
        self.newlabeldocument.forget()
        self.nuevo_documento.forget()
        self.nuevo_password.forget()
        self.boton_nuevo_registro.forget()
        self.labeluser.pack(side="top")
        self.usuario.pack(side="top")
        self.labelpass.pack(side="top")
        self.contraseña.pack(side="top")
        self.boton_iniciar_sesion.pack(side="top")
        self.boton_recuperar_contraseña.pack(side="top")
        self.boton_registrarse.pack(side="top")
    def Front_iniciar_sesion2(self):
        self.documento_recuperar_contraseña_label.forget()
        self.documento_recuperar_contraseña.forget()
        self.recuperar_contraseña.forget()
        self.contraseña_recuperar_label.forget()
        self.contraseña_recuperar_entry.forget()
        self.recuperar_contraseña_aceptar.forget()
        self.labeluser.pack(side="top")
        self.usuario.pack(side="top")
        self.labelpass.pack(side="top")
        self.contraseña.pack(side="top")
        self.boton_iniciar_sesion.pack(side="top")
        self.boton_recuperar_contraseña.pack(side="top")
        self.boton_registrarse.pack(side="top")
    def Front_iniciar_sesion3(self):
        self.documento_recuperar_contraseña_label.forget()
        self.documento_recuperar_contraseña.forget()
        self.recuperar_contraseña.forget()
        self.documento_recuperar_contraseña_label.forget()
        self.documento_recuperar_contraseña2.forget()
        self.documento_recuperar_contraseña_label.forget()
        self.documento_seleccion_dni_label.forget()
        self.documento_recuperar_contraseña_label.forget()
        self.documento_seleccion_dni_label.forget()
        self.recuperar_contraseña.forget()
        self.volver_al_inicio.forget()
        self.email_registro.forget()
        self.labeluser.pack(side="top")
        self.usuario.pack(side="top")
        self.labelpass.pack(side="top")
        self.contraseña.pack(side="top")
        self.boton_iniciar_sesion.pack(side="top")
        self.boton_recuperar_contraseña.pack(side="top")
        self.boton_registrarse.pack(side="top")
    def Back_iniciar_sesion(self):
        
        self.usuarios=self.usuario.get()
        #self.usuarios= str(self.usuarios)
        print(self.usuarios)
        self.contraseñas=self.contraseña.get()
        #self.contraseñas = str(self.contraseñas)
        inicio_sesion(self.usuarios,self.contraseñas)
    def Front_registrarse(self):
        self.boton_iniciar_sesion.forget()
        self.boton_recuperar_contraseña.forget()
        self.boton_registrarse.forget()
        self.labeluser.forget()
        self.labelpass.forget()
        self.usuario.forget()
        self.contraseña.forget()
        self.newlabeluser=ctk.CTkLabel(self.ventana0,text="nuevo usuario: ")
        self.newlabeluser.pack(side="top")
        self.nuevo_usuario= ctk.CTkEntry(self.ventana0)
        self.nuevo_usuario.pack(side="top")
        self.newlabelpass=ctk.CTkLabel(self.ventana0,text="nuevo password: ")
        self.newlabelpass.pack(side="top")
        
        self.nuevo_password= ctk.CTkEntry(self.ventana0)
        self.nuevo_password.pack(side="top")
        
        self.newlabelphone=ctk.CTkLabel(self.ventana0,text="nuevo celular: ")
        self.newlabelphone.pack(side="top")

        self.nuevo_celular= ctk.CTkEntry(self.ventana0)
        self.nuevo_celular.pack(side="top")

        self.newlabeldocument=ctk.CTkLabel(self.ventana0,text="nuevo documento: ")
        self.newlabeldocument.pack(side="top")
        self.nuevo_documento= ctk.CTkEntry(self.ventana0)
        self.nuevo_documento.pack(side="top")
        self.email_fnacimiento_label=ctk.CTkLabel(self.ventana0,text="fecha de nacimiento")
        self.email_fnacimiento_label.pack(side="top")
        self.fnacimientoentry= ctk.CTkEntry(self.ventana0)
        self.fnacimientoentry.pack(side="top")
        self.email_registroentry_label=ctk.CTkLabel(self.ventana0,text="email")
        self.email_registroentry_label.pack(side="top")
        self.email_registro_label=ctk.CTkEntry(self.ventana0)
        self.email_registro_label.pack(side="top")
        
        self.boton_nuevo_registro=ctk.CTkButton(self.ventana0,text="subir registro",command=self.subir_registro)
        self.boton_nuevo_registro.pack(side="top")
        self.boton_volver=ctk.CTkButton(self.ventana0,text="volver",command=self.subir_registro)
        self.boton_volver.pack(side="top")
    def subir_registro(self):
            self.nuevos_usuarios = self.nuevo_usuario.get()
            self.nuevos_passwords= self.nuevo_password.get()
            self.nuevos_celulares= self.nuevo_celular.get()
            self.nuevos_documentos= self.nuevo_documento.get()
            self.ffnacimientoentry= self.fnacimientoentry.get()
            self.femail_registro_label = self.email_registro_label.get()

            crear_usuario(self.nuevos_usuarios,self.nuevos_passwords,self.nuevos_celulares,self.nuevos_documentos,self.ffnacimientoentry,self.femail_registro_label)
            self.Front_iniciar_sesion1()

    def Front_olvido_contraseña(self): #########################################
        self.boton_iniciar_sesion.forget()
        self.boton_recuperar_contraseña.forget()
        self.boton_registrarse.forget()
        self.labeluser.forget()
        self.labelpass.forget()
        self.usuario.forget()
        self.contraseña.forget()
        
        self.documento_seleccion_dni_label=ctk.CTkLabel(self.ventana0,text="seleccione tipo de documentoxxx: ")
        self.documento_seleccion_dni_label.pack(side="top")
        self.documento_recuperar_contraseña2= ctk.CTkComboBox(self.ventana0,values=["DNI","otro documento"])
        self.documento_recuperar_contraseña2.pack(side="top")
        
        self.documento_recuperar_contraseña_label=ctk.CTkLabel(self.ventana0,text="ingrese documento: ")
        self.documento_recuperar_contraseña_label.pack(side="top")
        self.documento_recuperar_contraseña= ctk.CTkEntry(self.ventana0)
        self.documento_recuperar_contraseña.pack(side="top")
        self.email_registro=ctk.CTkButton(self.ventana0,text="email de registro")
        self.email_registro.pack(side="top")
        self.recuperar_contraseña=ctk.CTkButton(self.ventana0,text="ingresar",command=self.Back_olvido_contraseña)
        self.recuperar_contraseña.pack(side="top")
        self.volver_al_inicio=ctk.CTkButton(self.ventana0,text="volver al inicio",command=self.Front_iniciar_sesion3)
        self.volver_al_inicio.pack(side="top")
    def Back_olvido_contraseña(self):
        print("hola")
        self.recuperar_contraseña.forget()
        
        self.contraseña_recuperar_label=ctk.CTkLabel(self.ventana0,text="ingrese nueva contraseña: ")
        self.contraseña_recuperar_label.pack(side="top")
        
        self.contraseña_recuperar_entry=ctk.CTkEntry(self.ventana0)
        self.contraseña_recuperar_entry.pack(side="top")
        self.recuperar_contraseña_aceptar=ctk.CTkButton(self.ventana0,text="Aceptar",command=self.subir_nueva_contraseña)
        self.recuperar_contraseña_aceptar.pack(side="top")
        #cambiar_contraseña(self.documentos_recuperar_contraseñas,self.contraseña_recuperar_entry)
    def subir_nueva_contraseña(self):
        self.documentos_recuperar_contraseñas = self.documento_recuperar_contraseña.get()
        self.contraseñas_recuperar_entry = self.contraseña_recuperar_entry.get()
        cambiar_contraseña(self.documentos_recuperar_contraseñas,self.contraseñas_recuperar_entry)
        self.Front_iniciar_sesion2()


ejecuta=registro()